POST http://localhost:3023/transactions/661fcd231560a753d9967f0d
Content-Type: application/json

{
  "type": "income",
  "amount": 1700,
  "description": "Monthly salary",
  "date": "2024-03-20"
}

####

GET http://localhost:3023/transactions/661fcd231560a753d9967f0d